openapi: 3.0.0
# Added by API Auto Mocking Plugin
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: dng76@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'


paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets reader processed statistics
      responses:
        '200':
          description: Successfully returned a list of processed reader books
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/BookStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    BookStats:
      required:
        - genre_reader_pref
        - max_books_read
        - num_readers
        - num_books
      properties:
        genre_reader_pref:
          type: string
          example: 'Horror'
        max_books_read:
          type: integer
          example: 10
        num_readers:
          type: integer
          example: 100
        num_books:
          type: integer
          example: 100


      type: object